#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'charmie-carry-luggage','console_scripts','carry_my_luggage'
__requires__ = 'charmie-carry-luggage'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('charmie-carry-luggage', 'console_scripts', 'carry_my_luggage')()
    )
