# Select charmie arm ufactory mode movement and control variables 

string command                  # the name of the command
float32[] linear_motion_pose    # list of 6 variables ( x, y, z, roll, pitch, yaw) for linear motion adjustement
float32[] move_tool_line_pose   # list of 6 variables ( x, y, z, roll, pitch, yaw) for move tool line adjustement
float32[] joint_motion_values   # list of 6 variables, angle of each joint