# Message for omnidirectional adjustement of position considering closest obstacle

float32 distance            # distance to move forward
float32 direction           # direction to move in degrees
float32 ang_obstacle_check  # angle to check for obstacles when moving
float32 max_speed           # maximum linear speed
float32 tolerance           # tolerance for reaching the target position
float32 kp                  # proportional gain for the controller
