# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - xarm6_controller

  xarm6_controller:
    type: FollowJointTrajectory
    joints:
      - xarm_joint1
      - xarm_joint2
      - xarm_joint3
      - xarm_joint4
      - xarm_joint5
      - xarm_joint6