#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'charmie-stickler-for-the-rules','console_scripts','stickler_for_the_rules'
__requires__ = 'charmie-stickler-for-the-rules'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('charmie-stickler-for-the-rules', 'console_scripts', 'stickler_for_the_rules')()
    )
