#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'charmie-camera-realsense','console_scripts','camera_realsense'
__requires__ = 'charmie-camera-realsense'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('charmie-camera-realsense', 'console_scripts', 'camera_realsense')()
    )
