# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1:
    min_position: -6.28
    max_position: 6.28
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 10.0
  joint2:
    min_position: -2.05
    max_position: 2.05
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 10.0
  joint3:
    min_position: -3.92
    max_position: 0.19
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 10.0
  joint4:
    min_position: -6.28
    max_position: 6.28
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 10.0
  joint5:
    min_position: -1.69
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 10.0
  joint6:
    min_position: -6.28
    max_position: 6.28
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 10.0
