#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'charmie-inspection','console_scripts','inspection'
__requires__ = 'charmie-inspection'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('charmie-inspection', 'console_scripts', 'inspection')()
    )
