#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'charmie-door-start','console_scripts','door_start'
__requires__ = 'charmie-door-start'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('charmie-door-start', 'console_scripts', 'door_start')()
    )
