radar_node:
  robot_base_frame: base_footprint
  observation_sources: scan scan_bottom
  scan:
    topic: /scan
    max_obstacle_height: 1.8
    min_obstacle_height: 0.0
    data_type: "LaserScan"
    obstacle_max_range: 5.5
    obstacle_min_range: 0.05
  scan_bottom:
    topic: /scan_bottom
    max_obstacle_height: 1.8
    min_obstacle_height: 0.0
    data_type: "LaserScan"
    obstacle_max_range: 5.5
    obstacle_min_range: 0.05