radar_node:
  robot_base_frame: base_footprint # frame of the robot base
  robot_radius: 0.28 # radius of the robot in meters
  update_frequency: 10.0 # frequency to update the radar data in Hz
  observation_sources: scan scan_bottom livox_lidar
  scan:
    topic: /scan
    data_type: "LaserScan"
    obstacle_min_range: 0.05
    obstacle_max_range: 5.5
    min_obstacle_height: 0.0
    max_obstacle_height: 1.8
  scan_bottom:
    topic: /scan_bottom
    data_type: "LaserScan"
    obstacle_min_range: 0.05
    obstacle_max_range: 5.5
    min_obstacle_height: 0.0
    max_obstacle_height: 1.8
  livox_lidar:
    topic: /livox/lidar
    data_type: "PointCloud2"
    publish_filtered: True
    obstacle_min_range: 0.1   # as per the datasheet: Close proximity blind zone of 0.1 meters. 
    obstacle_max_range: 30.0  # as per the datasheet: Has a detection range of 40 meters at 10% reflectivity and 70 meters at 80% reflectivity. 
    min_obstacle_height: 0.3  # to ignore floor noise
    max_obstacle_height: 1.8  # to ignore ceiling noise (obstacles above the robot height) 