radar_node:
  robot_base_frame: base_footprint # frame of the robot base
  robot_radius: 0.29 # radius of the robot in meters
  update_frequency: 10.0 # frequency to update the radar data in Hz
  radar_configuration:
    number_of_sectors: 32
    min_radar_angle: -1.57079633 # -90 degrees # -2.0944 # -120 degrees
    max_radar_angle:  1.57079633 #  90 degrees #  2.0944 # +120 degrees
    max_radar_dist: 5.0 # maximum distance to consider for radar data in meters
    # DO NOT CHANGE MAX_RADAR_DIST -> THIS VALUE IS CONNECTED TO THE REINFORCEMENT LEARNING MODEL TRAINED
    # SHOULD ONLY BE CHANGED IF THE RL MODEL IS RE-TRAINED WITH A DIFFERENT VALUE
  observation_sources: scan scan_bottom livox_lidar  
  scan:
    topic: /scan
    data_type: "LaserScan"
    min_obstacle_range: 0.05
    max_obstacle_range: 5.5
    min_obstacle_height: 0.0
    max_obstacle_height: 1.8
    min_obstacle_angle: -3.1416 # -180 degreces
    max_obstacle_angle:  3.1416 # +180 degrees
  scan_bottom:
    topic: /scan_bottom
    data_type: "LaserScan"
    min_obstacle_range: 0.05
    max_obstacle_range: 5.5
    min_obstacle_height: 0.0
    max_obstacle_height: 1.8
    min_obstacle_angle: -3.1416 # -180 degrees
    max_obstacle_angle:  3.1416 # +180 degrees
  livox_lidar:
    topic: /livox/lidar
    data_type: "PointCloud2"
    publish_filtered: True # publish_filtered is only available for PointCloud2 data type
    min_obstacle_range: 0.1 # as per the datasheet: Close proximity blind zone of 0.1 meters. 
    max_obstacle_range: 10.0 # 30.0  # as per the datasheet: Has a detection range of 40 meters at 10% reflectivity and 70 meters at 80% reflectivity. 
    min_obstacle_height: 0.25  # to ignore floor noise
    max_obstacle_height: 1.65  # to ignore ceiling noise (obstacles above the robot height) 
    min_obstacle_angle: -2.0944 # -120 degrees
    max_obstacle_angle:  2.0944 # +120 degrees