sdnl_nav:
  ros__parameters:
    # Rates
    control_rate_hz: 30.0
    debug_enabled: true
    debug_rate_hz: 10.0
    n_samples: 720

    # Topics
    topic_robot_localisation: "robot_localisation"
    topic_radar_data: "radar/data"
    topic_cmd_vel: "cmd_vel"
    topic_sdnl_debug: "sdnl/debug"

    # SDNL major params
    lambda_target_not_obs:  1.0
    lambda_target_with_obs: 0.8
    beta1: 2.0
    beta2: 5.0

    # SDNL minor params
    max_dist_for_obs: 2.0
    robot_radius: 0.32 # 0.28
    heading_offset_rad: 0.0
    use_obstacle_cutoff: false
        
    # Linear velocity control params
    # Target slowdown
    tar_slow_dist: 1.0   # [m]   start slowing down distance from reached radius
    tar_min_dist: 0.20    # [m]   distance from reached radius at which we reach minimum speed due
    v_tar_min_frac: 0.20  # [m/s] min v fraction when for target slowdown

    # Obstacle slowdown
    obs_slow_dist: 1.0   # [m]   start slowing down due to obstacles
    obs_min_dist: 0.20    # [m]   distance at which we reach minimum speed due to obstacles
    v_obs_min_frac: 0.20  # [m/s] min v fraction when obstacles are present

    # Turning slowdown
    v_turn_min_frac: 0.10 # [m/s] min v fraction when turning hard

    # Controller constraints
    default_max_linear_speed: 0.42
    default_max_angular_speed: 0.9

    # Thresholds
    default_reached_radius: 0.5
    default_yaw_tolerance: 0.052359908 # ~3 degrees in radians

