<?xml version="1.0"?>
<robot name="charmie" xmlns:xacro="http://www.ros.org/wiki/xacro">
    

    <xacro:property name="base_octagon_side" value="0.232" />
    <xacro:property name="base_length" value="0.56" />
    <xacro:property name="base_height" value="0.27" />

    <xacro:property name="base_floor_height" value="0.05" />
    
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.038" />
    <xacro:property name="wheel_shift_from_base_length" value="0.025" />


    <material name ="orange">
        <color rgba="1 0.3 0.1 1" />
    </material>
    
    <material name ="black">
        <color rgba="0 0 0 1" />
    </material>
    
    <material name ="light_grey">
        <color rgba="0.8 0.8 0.8 1" />
    </material>


    <!-- BASE LINK -->

    <link name="base_link">

        <visual>
            <geometry>
                <box size="${base_length} ${base_octagon_side} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
            <material name="light_grey"/>
        </visual>

        <visual>
            <geometry>
                <box size="${base_length} ${base_octagon_side} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 ${pi/2}" />
            <material name="light_grey"/>
        </visual>

        <visual>
            <geometry>
                <box size="${base_length} ${base_octagon_side} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 ${pi/4}" />
            <material name="light_grey"/>
        </visual>

        <visual>
            <geometry>
                <box size="${base_length} ${base_octagon_side} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 -${pi/4}" />
            <material name="light_grey"/>
        </visual>

    </link>


    <!-- BASE FOOTPRINT -->
      
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${base_floor_height}" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">

    </link> 


    <!-- LIDAR -->

    <!-- <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_lidar"/>
        <origin xyz="0.265 0.0 0.35"/>
    </joint>

    <link name="base_lidar">
        <visual>
            <geometry>
                <cylinder radius="0.019" length="0.024" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="black"/>
        </visual>

    </link> -->

    <!-- WHEEL LINK FUNCTION -->

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <material name="black"/>
            </visual>
        </link>
    </xacro:macro>

    <!-- RIGHT WHEEL -->

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0 ${-(base_length/2-wheel_shift_from_base_length)} ${wheel_radius-base_floor_height}"/>
        <axis xyz="0 1 0"/>
    </joint>

    <xacro:wheel_link prefix="right" />

    <!-- LEFT WHEEL -->

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0 ${+(base_length/2-wheel_shift_from_base_length)} ${wheel_radius-base_floor_height}"/>
        <axis xyz="0 1 0"/>
    </joint>

    <xacro:wheel_link prefix="left" />

    <!-- FRONT CASTER WHEEL -->

    <joint name="base_front_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_caster_wheel_link"/>
        <origin xyz="${+(base_length/2-base_floor_height/2)} 0 ${-base_floor_height/2}"/>
    </joint>


    <link name="front_caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${base_floor_height/2}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="black"/>
        </visual>
    </link>

    <!-- BACK CASTER WHEEL -->

    <joint name="base_back_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="back_caster_wheel_link"/>
        <origin xyz="${-(base_length/2-base_floor_height/2)} 0 ${-base_floor_height/2}"/>
    </joint>


    <link name="back_caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${base_floor_height/2}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="black"/>
        </visual>
    </link>


</robot>