<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="camera_dist_from_face_link" value="${face_length + head_camera_length}" />
    <xacro:property name="camera_height_from_face_link" value="${face_height_shift+face_height/2-head_camera_height/2-0.008}" />
    
    <xacro:property name="head_camera_length" value="0.034" />
    <xacro:property name="head_camera_width" value="0.145" />
    <xacro:property name="head_camera_height" value="0.052" />

    <!-- Temporary adjustements (compared to older face) for updated face 2025_06 -->
    <xacro:property name="adjust_for_temp_face_x" value="0.0045" />
    <xacro:property name="adjust_for_temp_face_y" value="0.0" />
    <xacro:property name="adjust_for_temp_face_z" value="-0.075" />

    <joint name="head_camera_joint" type="fixed">
        <parent link="face_link"/>
        <child link="head_camera_link"/>
        <origin xyz="${camera_dist_from_face_link+adjust_for_temp_face_x} 0 ${camera_height_from_face_link+adjust_for_temp_face_z}" rpy="0 0 0"/>
    </joint>

    <link name="head_camera_link">

        <visual>
            <origin xyz="${-head_camera_length/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${head_camera_length} ${head_camera_width} ${head_camera_height}" />
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <origin xyz="${-head_camera_length/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${head_camera_length} ${head_camera_width} ${head_camera_height}" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${head_camera_length}" y="${head_camera_width}" z="${head_camera_height}" >
            <origin xyz="${-head_camera_length/2} 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
        
    </link>

</robot>