<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:property name="base_octagon_side" value="0.232" />
    <xacro:property name="base_length" value="0.56" />
    <xacro:property name="base_height" value="0.27" />

    <xacro:property name="base_floor_height" value="0.05" />
    
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.038" />
    <xacro:property name="wheel_shift_from_base_length" value="0.025" />

    <!-- BASE LINK -->

    <link name="base_link">

        <visual>
            <geometry>
                <box size="${base_length} ${base_octagon_side} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
            <material name="light_grey"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_octagon_side} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
        </collision>
        <xacro:inertial_box mass="5.0" x="${base_length}" y="${base_octagon_side}" z="${base_height}" >
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
        </xacro:inertial_box>

        <visual>
            <geometry>
                <box size="${base_length} ${base_octagon_side} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 ${pi/2}" />
            <material name="light_grey"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_octagon_side} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 ${pi/2}" />
        </collision>
        <xacro:inertial_box mass="5.0" x="${base_length}" y="${base_octagon_side}" z="${base_height}" >
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 ${pi/2}" />
        </xacro:inertial_box>

        <visual>
            <geometry>
                <box size="${base_length} ${base_octagon_side} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 ${pi/4}" />
            <material name="light_grey"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_octagon_side} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 ${pi/4}" />
        </collision>
        <xacro:inertial_box mass="5.0" x="${base_length}" y="${base_octagon_side}" z="${base_height}" >
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 ${pi/4}" />
        </xacro:inertial_box>

        <visual>
            <geometry>
                <box size="${base_length} ${base_octagon_side} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 -${pi/4}" />
            <material name="light_grey"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_octagon_side} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 -${pi/4}" />
        </collision>
        <xacro:inertial_box mass="5.0" x="${base_length}" y="${base_octagon_side}" z="${base_height}" >
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 -${pi/4}" />
        </xacro:inertial_box>

    </link>


    <!-- BASE FOOTPRINT -->
      
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 ${-base_floor_height}" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">

    </link> 

    <!-- WHEEL LINK FUNCTION -->

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <!-- <mesh filename="file://$(find charmie_description)/meshes/omni_wheel.stl" scale="0.001 0.001 0.001"/> -->
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </collision>
            <xacro:inertial_cylinder mass="0.5" length="${wheel_length}" radius="${wheel_radius}" >
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            </xacro:inertial_cylinder>
        </link>
    </xacro:macro>

    <!-- RIGHT WHEEL -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0 ${-(base_length/2-wheel_shift_from_base_length)} ${wheel_radius-base_floor_height}"/>
        <axis xyz="0 1 0"/>
    </joint>

    <xacro:wheel_link prefix="right" />

    <!-- LEFT WHEEL -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0 ${+(base_length/2-wheel_shift_from_base_length)} ${wheel_radius-base_floor_height}"/>
        <axis xyz="0 1 0"/>
    </joint>

    <xacro:wheel_link prefix="left" />

    <!-- FRONT CASTER WHEEL -->

    <joint name="base_front_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_caster_wheel_link"/>
        <origin xyz="${+(base_length/2-base_floor_height/2)} 0 ${-base_floor_height/2}"/>
    </joint>


    <link name="front_caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${base_floor_height/2}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${base_floor_height/2}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:inertial_sphere mass="0.5" radius="${base_floor_height/2}" >
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_sphere>
    </link>

    <!-- BACK CASTER WHEEL -->

    <joint name="base_back_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="back_caster_wheel_link"/>
        <origin xyz="${-(base_length/2-base_floor_height/2)} 0 ${-base_floor_height/2}"/>
    </joint>


    <link name="back_caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${base_floor_height/2}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${base_floor_height/2}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:inertial_sphere mass="0.5" radius="${base_floor_height/2}" >
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_sphere>
    </link>


</robot>