# Service to activate variables that just need a boolean

bool activate   # activate or deactivate
---
bool success    # indicate successful run of triggered service
string message  # informational, e.g. for error messages.