# Service to activate the yolo world detection, thus publishing it on the topic

bool activate_prompt_free_head          # activate or deactivate prompt free detection for head camera
bool activate_tv_prompt_head            # activate or deactivate text and visual prompt detection for head camera
bool activate_prompt_free_hand          # activate or deactivate prompt free detection for gripper camera
bool activate_tv_prompt_hand            # activate or deactivate text and visual prompt detection for gripper camera
bool activate_prompt_free_base          # activate or deactivate prompt free detection for base camera
bool activate_tv_prompt_base            # activate or deactivate text and visual prompt detection for base camera
float64 minimum_prompt_free_confidence  # set minimum confidence value for prompt free detections
float64 minimum_tv_prompt_confidence    # set minimum confidence value for text and visual prompt detections
string[] text_prompts
---
bool success    # indicate successful run of triggered service
string message  # informational, e.g. for error messages.