# Set which keywords must the robot hear to exit audio continuous mode

string[] keywords # words the robot must hear to answer the service
int32 max_number_attempts # max number of attempts for audio, just for safety
---
bool success    # indicate successful run of triggered service
string message  # informational, e.g. for error messages.