# Service to get the LLM response, using the offline ollama LLM

string command          # The command to be sent to the LLM
int32 mode              # defines the operation mode for the LLM
---
ListOfStrings answer    # List of sub tasks divisions the robot must perform to complete a task