# List of nodes being used by a task node just for debug when using the gui_debug

bool charmie_arm
bool charmie_audio
bool charmie_face
bool charmie_head_camera
bool charmie_hand_camera
bool charmie_base_camera
bool charmie_gamepad
bool charmie_lidar
bool charmie_lidar_bottom
bool charmie_lidar_livox
bool charmie_llm
bool charmie_localisation
bool charmie_low_level
bool charmie_navigation
bool charmie_nav2
bool charmie_neck
bool charmie_radar
bool charmie_sound_classification
bool charmie_speakers
bool charmie_tracking
bool charmie_yolo_objects
bool charmie_yolo_pose
bool charmie_yolo_world
---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages.