# Service to send an acceleration ramp for motors 

int32 data # value of motors acceleration ramp
---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages.