# Service to set the face touchscreen menu 

string[] command # options for the face touchscreen menu
---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages.