# Service to set a PoseWithCovarianceStamped message

geometry_msgs/PoseWithCovarianceStamped pose  # PoseWithCovarianceStamped pose to be set
---
bool success    # indicate successful run of triggered service
string message  # informational, e.g. for error messages.