# Service to set a string

string data # informational, e.g. for error messages.
---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages.
