controller_manager:
  ros__parameters:
    update_rate: 100
    #use_sim_time: true

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      #- camera_joint_y
      #- camera_joint_z
      - upper_body_joint
      - lower_body_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity