# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  xarm_gripper_drive_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 10.0
  xarm_gripper_left_finger_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 10.0
  xarm_gripper_left_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 10.0
  xarm_gripper_right_finger_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 10.0
  xarm_gripper_right_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 10.0
  xarm_gripper_right_outer_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 10.0
  xarm_joint1:
    min_position: -6.28
    max_position: 6.28
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 10.0
  xarm_joint2:
    min_position: -2.05
    max_position: 2.05
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 10.0
  xarm_joint3:
    min_position: -3.92
    max_position: 0.19
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 10.0
  xarm_joint4:
    min_position: -6.28
    max_position: 6.28
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 10.0
  xarm_joint5:
    min_position: -1.69
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 10.0
  xarm_joint6:
    min_position: -6.28
    max_position: 6.28
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 10.0